// Class automatically generated by Dev-C++ New Class wizard

#ifndef BLIP_H
#define BLIP_H

/*
 * No description
 */
class Blip
{
	public:
        int id;
        int xloc;
        int yloc;
        
	// class constructor
	Blip(int startx, int starty);
	// class destructor
	~Blip();
	// Change internal blip location
	move(int newX, int newY)
		
};

class Cell : class Blip
{
    	public:
	// class constructor
	Cell();
	// class destructor
	~Cell();
};


#endif // BLIP_H
